### ISSUE TITLE
Response Codes Description

### ISSUE THREAD

**Issue by frandelarosa** [HMS-Core/hms-push-serverdemo-nodejs#2]
Hello,

Can be useful adding a description for each response code which is returned by API.

```
"code": "80000000",
"msg": "Success",
"requestId": "159497776740744939000507"
```

For instance, in this case, the message has been sent, but the field named "code" has a value that in my opinion it's not very intuitive. A enum with all cases could be a good choice to control any behaviour.

Regards,
Fran

**Comment by Mike-mei** [comment]
Thank you for your advice, we will consider to add this in the future version.
For more information about API error code, you can refer to this link: https://developer.huawei.com/consumer/en/doc/development/HMSCore-References-V5/https-send-api-0000001050986197-V5#EN-US_TOPIC_0000001050986197__section13968115715131
