### ISSUE TITLE
can not find file "request-promise".

### ISSUE THREAD

**Issue by Joseph-Nathan** [HMS-Core/hms-push-serverdemo-nodejs#5]
utils/api-request.ts:21:16 - error TS2307: Cannot find module 'request-promise' or its corresponding type declarations.

21 import rp from "request-promise";

**Comment by Mike-mei** [comment]
Please don't add your own logic and use this demo directly.

**Comment by Joseph-Nathan** [comment]
As of Feb 11th 2020, request is fully deprecated. No new changes are expected to land. In fact, none have landed for some time. "request-promise" package is also deprecated because it depends on request.

please i can not get this package to used .

**Comment by Joseph-Nathan** [comment]
sorry i install it in different  dir ,
